Add ability to use parameters defined in the service container
Codeception/module-phalcon pull request #3
Opened 2020-01-02 07:18 UTC by debugger84

The parameter $parameters of the method get of the Phalcon's DiInterface can be array or null.

```
/**
     * Resolves the service based on its configuration
     *
     * @param string $name
     * @param array $parameters
     * @return mixed
     */
    public function get($name, $parameters = null);
```

According to this parameter Di container tries to create service. If we have an array of dependencies in our definition, such as 
```
'group' => [
         'className' => '\Acme\Group',
         'arguments' => [
             [
                 'type' => 'service',
                 'service' => 'myComponent',
             ],
         ],
     ],
```

than we can get \Acme\Group without parameters `$group = $container->get('group', null);`. In this case we get class Group with injected myComponete.
If we use `$group = $container->get('group', []);`, than we have got an error " [ArgumentCountError] Too few arguments to function Acme\Group::__construct(), 0 passed and exactly 1 expected ".

This pull request adds an ability to use parameters from the container's definition, to create a service.

2020-01-02 10:15 UTC, Naktibalda commented
This small change raises the lowest supported version of PHP to 7.1

2020-01-03 16:46 UTC, sergeyklay requested changes
We can't break BC with this small change. At least for a minor module version. Consider to use `array $parameter = null` instead

2020-01-03 16:46 UTC, sergeyklay commented on src/Codeception/Module/Phalcon.php
> +    public function grabServiceFromContainer($service, ?array $parameters = [])
```suggestion
    public function grabServiceFromContainer($service, array $parameters = null)
```

2020-01-06 07:49 UTC, debugger84 commented on src/Codeception/Module/Phalcon.php
> +    public function grabServiceFromContainer($service, ?array $parameters = [])
Done

2020-01-06 09:20 UTC, sergeyklay approved these changes
/cc @Naktibalda

2020-01-06 11:28 UTC, merged

2020-01-06 11:38 UTC, Naktibalda commented
I think that this change is a feature, so it must be released as 1.1.0, is that right?

2020-01-06 18:47 UTC, sergeyklay commented
Yes, I think so